#!/bin/bash

masses=(
#	800
	1000
	1200
	1400
#	1600
)

n_events=400000
#n_events=4000

function RunOneMass()
{
	dir="m_X_$mass"
	mkdir -p "$dir"

	cat "template_cfg.py"|sed "\
			s|\$mass|$mass|g;\
			s|\$n_events|$n_events|g;\
		" > "$dir/cfg.py"

	cd "$dir"

	cmsRun "cfg.py" &> "log" &

	cd - &> /dev/null
}

for mass in ${masses[*]}
do
	RunOneMass $mass
done
