#!/bin/bash

function SubmitOneDir()
{
	local tag="$1"
	local selection="$2"
	local top_dir="$3"

	local buf="$tag"

	fill=${buf#fill}
	fill=${fill%%_*}

	buf=${buf#*_}
	xangle=${buf%%_*}
	xangle=${xangle#xangle}

	buf=${buf#*_}
	beta=${buf%%_*}
	beta=${beta#beta}

	buf=${buf#*_}
	stream=${buf%%.*}

	# skip fills that don't have the CondDB data yet
	if [ $fill -lt 6744 ]
	then
		continue
	fi

	echo "* $fill, $xangle, $beta, $stream"

	# get input
	input=""
	for f in `eos ls "$eos_dir"|grep $tag|grep "$selection"|grep .root`
	do
		if [ -n "$input" ]
		then
			input="$input\n"
		fi

		input="${input}process.source.fileNames.append(\"root://eostotem.cern.ch/${eos_dir}/${f}\")"
	done

	for alignment in ${alignments[*]}
	do
		echo "  $alignment"

		# make work directory
		dir="$top_dir/fill_$fill/xangle_${xangle}_beta_${beta}/$stream/alignment_$alignment"
		mkdir -p "$dir"
		rm -rf "$dir/output.root"

		full_dir="`pwd -P`/$dir"

		# make config with input files
		cat "template_cfg.py" | sed -e "\
				s|\$input|$input|g;\
				s|\$fill|$fill|g;\
				s|\$xangle|$xangle|g;\
				s|\$beta|$beta|g;\
				s|\$alignment|$alignment|g;\
				s|\$output|output.root|g;\
			" > "$dir/cfg.py"

		# make job
		cat "template_job" | sed "\
				s|\$job_dir|$full_dir|g;\
				s|\$CMSSW_BASE|$CMSSW_BASE|g;\
			" > "$dir/job"
		chmod u+x "$dir/job"

		# submit
		result=`bsub -q $queue -o /dev/null -e /dev/null "$full_dir/job"`
		echo "    $result"
	done
}

#----------------------------------------------------------------------------------------------------

function SubmitOneGroup()
{
	local selection="$1"
	local top_dir="$2"

	for tag in `eos ls "$eos_dir"|grep "$selection"|grep ZeroBias|grep .root|uniq`
	do
		SubmitOneDir "$tag" "$selection" "$top_dir"
	done
}

#----------------------------------------------------------------------------------------------------

queue="8nh"

eos_dir="/eos/totem/data/ctpps/reconstruction/2018/physics_runs/version2"

alignments=(
	"2018_11_02.3"
)

SubmitOneGroup "xangle140" "data_eos/"
